version: "3.8"
services:
  # Database, using mysql
  db:
    image: mysql:8.0
    container_name: db_ecom_symfony
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: test
    networks:
      - dev

  # PHPMyAdmin linked to our mysql db    
  phpmyadmin:
    image: phpmyadmin:5.0
    container_name: phpmyadmin_ecom_symfony
    restart: always
    # This service needs another service, so we wait for "db" service to start before starting phpmyadmin (with depends_on)
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
    networks:
      - dev

  # MailDev for checking emails sent during dev   
  maildev:
    image: maildev/maildev
    container_name: maildev_ecom_symfony
    # Use this command to prevent error message when sending mails from symfony app
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - "8081:80"
    restart: always
    networks:
      - dev         

  # PHP and Apache container, using our custom image in Dockerfile (using build instead of image here)    
  www:
    build: php # Name of the repository where you can find the Dockerfile used for building the image
    container_name: www_ecom_symfony
    ports:
      - "8741:80"
    volumes:
      - ./php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      - dev  
      
networks:
  dev:

volumes:
  db-data:        